# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-scheduler:
      repo: 'https://github.com/EOSC-synergy/saps-scheduler'
      branch: develop

sqa_criteria:
   qc_coverage:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           - ls -la
           - pwd
           - mvn -B -DskipTests clean package
           - mvn test
