# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-scheduler:
      repo: 'https://github.com/EOSC-synergy/saps-scheduler'
      branch: develop
    saps-common:
      repo: 'https://github.com/EOSC-synergy/saps-common'
      branch: develop
    saps-catalog:
      repo: 'https://github.com/EOSC-synergy/saps-catalog'
      branch: develop

sqa_criteria:
   qc_style:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
         # saps-scheduler has saps-common and saps-catalog as dependences and must be installed
           - mvn -f /saps-common-repo/pom.xml install
           - mvn -f /saps-catalog-repo/pom.xml install
           - mvn -f /saps-scheduler-repo/pom.xml checkstyle:checkstyle
   qc_coverage:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           - mvn -f /saps-scheduler-repo/pom.xml -B -DskipTests clean package
           - mvn -f /saps-scheduler-repo/pom.xml test

   qc_security:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           #- wget https://github.com/spotbugs/spotbugs/releases/download/4.2.1/spotbugs-4.2.1.tgz
           #https://oss.sonatype.org/content/repositories/snapshots/com/github/spotbugs/spotbugs-maven-plugin/4.2.1-SNAPSHOT/
           #- tar -xzvf spotbugs-4.2.1.tgz
           #- mvn -f /saps-scheduler-repo/pom.xml -B -DskipTests clean package
           #- mvn -f /saps-scheduler-repo/pom.xml spotbugs:spotbugs
           - mvn compile site

   qc_doc:
     repos:
       saps-scheduler:
         container: scheduler-docs
         commands:
           - pip install recommonmark
           - make html -C /saps-scheduler-repo/docs/

