# .sqa/config.yml - jenkins-pipeline-library configuration file
config:
  project_repos:
    saps-scheduler:
      repo: 'https://github.com/EOSC-synergy/saps-scheduler'
      branch: develop

sqa_criteria:
   qc_coverage:
     repos:
       saps-scheduler:
         container: scheduler-testing
         commands:
           - pwd
           - /usr/bin/mvn -f /scheduler-testing/pom.xml -B -DskipTests clean package
           - /usr/bin/mvn -f /scheduler-testing/pom.xml test
